name: Ejecutar Hola Mundo

on:
  workflow_dispatch:      # Para que lo puedas lanzar manualmente
  schedule:
    - cron: '0 * * * *'   # Ejecutar cada hora (opcional)

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar script
        run: python HoloMundo.py
